services:
  buses:
    image: aayushjn/travelms-buses:1.0
    container_name: travelms-buses
    restart: unless-stopped
    networks:
      - travelms
  hotels:
    image: aayushjn/travelms-hotels:1.0
    container_name: travelms-hotels
    restart: unless-stopped
    networks:
      - travelms
  users:
    image: aayushjn/travelms-users:1.0
    container_name: travelms-users
    restart: unless-stopped
    networks:
      - travelms
  packages:
    image: aayushjn/travelms-packages:1.0
    container_name: travelms-packages
    restart: unless-stopped
    networks:
      - travelms
    depends_on:
      - buses
      - hotels
  booking:
    image: aayushjn/travelms-booking:1.0
    container_name: travelms-booking
    restart: unless-stopped
    networks:
      - travelms
    depends_on:
      - users
      - packages
  nginx:
    image: nginx:1.25.4
    container_name: gateway
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf
    restart: unless-stopped
    volumes:
      - ./config/nginx/default.conf.conf:/etc/nginx/templates/default.conf.conf
    ports:
      - 8000:80
    networks:
      - travelms
    depends_on:
      - booking

networks:
  travelms: