spring:
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
  mvc:
    problemdetails:
      enabled: true
travelms:
  services:
    users: gateway/users
    packages: gateway/packages